import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./global.css";
import { Provider } from "react-redux";
import ThemeInjector from "./_infra-components/theme/ThemeInjector";
import { store } from "./_state/store";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeInjector />
      <body className={inter.className}>{children}</body>
    </html>
  );
}
